// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD8Wg3yu1LPx0RP9b3G5yv3Caoc8SlDdJ8',
    appId: '1:502037806566:web:de1ad28172d2869e9f2a27',
    messagingSenderId: '502037806566',
    projectId: 'graduate-skill-sets',
    authDomain: 'graduate-skill-sets.firebaseapp.com',
    storageBucket: 'graduate-skill-sets.appspot.com',
    measurementId: 'G-H7ZESTP784',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAlDOWk1zP4VSGgGDdZ2BXZiokw0HZp8Ho',
    appId: '1:502037806566:android:fab9466264cb7fb29f2a27',
    messagingSenderId: '502037806566',
    projectId: 'graduate-skill-sets',
    storageBucket: 'graduate-skill-sets.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDEve-XF1V7eGYZiIm5TUC4OiLIgJ_5ops',
    appId: '1:502037806566:ios:f4a041e2f9096a1f9f2a27',
    messagingSenderId: '502037806566',
    projectId: 'graduate-skill-sets',
    storageBucket: 'graduate-skill-sets.appspot.com',
    iosClientId: '502037806566-ov5ldkie8rn8nc94f7hfni3t91dbc85u.apps.googleusercontent.com',
    iosBundleId: 'com.example.gp.RunnerTests',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDEve-XF1V7eGYZiIm5TUC4OiLIgJ_5ops',
    appId: '1:502037806566:ios:f4a041e2f9096a1f9f2a27',
    messagingSenderId: '502037806566',
    projectId: 'graduate-skill-sets',
    storageBucket: 'graduate-skill-sets.appspot.com',
    iosClientId: '502037806566-ov5ldkie8rn8nc94f7hfni3t91dbc85u.apps.googleusercontent.com',
    iosBundleId: 'com.example.gp.RunnerTests',
  );
}
